---
title: "keyATM with validateIT"
author: "Tomoya Sasaki"
date: "8/10/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
aws_key <- read.table("/Users/tomoyasasaki/rootkey.csv", sep = ",")
# aws_key <- read.csv("/Users/tomoyasasaki/new_user_credentials.csv")
```


```{r, message = FALSE}
library(keyATM)
library(quanteda)
library(magrittr)
library(stm)
library(validateIt) # make sure to compile from the local folder
```


# Prepare documents
* From the example in the website

```{r}
data(data_corpus_inaugural, package = "quanteda")

data_tokens <- tokens(data_corpus_inaugural,
                      remove_numbers = TRUE,
                      remove_punct = TRUE,
                      remove_symbols = TRUE,
                      remove_separators = TRUE,
                      remove_url = TRUE) %>%
                 tokens_tolower() %>%
                 tokens_remove(c(stopwords("english"),
                               "may", "shall", "can",
                               "must", "upon", "with", "without")) %>%
                 tokens_select(min_nchar = 3)
data_dfm <- dfm(data_tokens) %>%
              dfm_trim(min_termfreq = 5, min_docfreq = 2)
```

# Pre-process for validateIt

```{r}
heldout <- make.heldout(data_dfm, seed = 123)
```

# keyATM
```{r, message = FALSE}
# convert heldout object to keyATM object
df_heldout <- matrix(0, nrow = length(heldout$documents), ncol = length(heldout$vocab))
row.names(df_heldout) <- names(heldout$documents)
colnames(df_heldout) <- heldout$vocab

for (i in 1:length(heldout$documents)) {
  obj <- heldout$documents[[i]]
  for (j in 1:ncol(obj)) {
    id <- obj[1, j]
    num <- obj[2, j]
    df_heldout[i, id] <- df_heldout[i, id] + num
  }
}

keyATM_docs <- keyATM_read(texts = as.dfm(df_heldout))
# keywords
keywords <- list(Government     = c("laws", "law", "executive"),
                 Congress       = c("congress", "party"),
                 Peace          = c("peace", "world", "freedom"),
                 Constitution   = c("constitution", "rights"),
                 ForeignAffairs = c("foreign", "war"))
# run
out <- keyATM(docs              = keyATM_docs,    # text input
              no_keyword_topics = 5,              # number of topics without keywords
              keywords          = keywords,       # keywords
              model             = "base",         # select the model
              options           = list(seed = 250, iterations = 100))
```

# stm
```{r, message = FALSE}
# out2 <- stm(documents = heldout$documents, heldout$vocab, K = 10, max.em.its = 50, seed = 250, verbose = FALSE)
```

# Create a screen
* This link is helpful \url{https://blog.mturk.com/tutorial-setting-up-your-aws-account-to-make-use-of-mturks-api-4e405b8fc8cb}
* In addition to the step described in the blog, you also need to complete "Register for the MTurk Developer Sandbox"

```{r}
library(pyMTurkR)
Sys.setenv(AWS_ACCESS_KEY_ID = aws_key[1, 2])
Sys.setenv(AWS_SECRET_ACCESS_KEY = aws_key[2, 2])
options(pyMTurkR.sandbox = F) # change sandbox = F when ready to run on MTurk 
AccountBalance()
```

```{r}
TestQuestions <- paste0(readLines("T8WSIQuestion.xml", # you may need to add a file path 
                                  warn = FALSE), collapse = "")
TestKey <- paste0(readLines("T8WSIAnswer.xml",
                            warn = FALSE),
                  collapse = "")
```

```{r, eval = FALSE}
T8WSIQual <- CreateQualificationType(name = "top eight word set intrusion qualification 2", # name of the qualification
                                     description =  'Qualification for "top eight word set intrusion" tasks 2.' , # description of the qualification
                                     status = "Active", # allows qual to remain active for users
                                     test = TestQuestions, # pass questions for qual test
                                     test.duration = 60 * 60, # test duration, in seconds
                                     retry.delay = NULL, # how long until worker can retry test; NULL means never
                                     answerkey = TestKey)
```


```{r}
out_keyatm <- combMass(out, beta = out$phi, vocab = out$vocab)
# out_stm <- combMass(out2)
```


```{r}
T8WSItasks <- validateTopic(type = "T8WSI", 
                            n = 500,
                            text = data_corpus_inaugural[-heldout$missing$index],
                            vocab = out_keyatm[[1]],
                            beta = out_keyatm[[2]],
                            theta = out$theta[-heldout$missing$index, ],
                            thres = 20)
```


```{r, eval=FALSE}
```

